routes/web.php
<?php

use App\Http\Controllers\AuthController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::get('/dashboard', function () {
    
//     return view('index');
// })->middleware(['auth'])->name('dashboard');


Route::get('logout', [AuthController::class, 'logout'])->name('logout.manual');
Route::get('index', [AuthController::class, 'index'])->name('index');
Route::get('dashboard', [AuthController::class, 'index'])->name('index');

Route::resource('info', App\Http\Controllers\InfoController::class);
Route::resource('menu', App\Http\Controllers\MenuController::class);
Route::get('/menu/{id}/delete', [App\Http\Controllers\MenuController::class, 'destroy'])->name('menu.destroy');


Route::resource('role', App\Http\Controllers\RoleController::class);
Route::get('/role/{id}/delete', [App\Http\Controllers\RoleController::class, 'destroy'])->name('role.destroy');


Route::resource('rolemenu', App\Http\Controllers\MenuRoleController::class);
Route::get('/rolemenu/{id}/delete', [App\Http\Controllers\MenuRoleController::class, 'destroy'])->name('rolemenu.destroy');



require __DIR__.'/auth.php';

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Role extends Model
{
    use HasFactory, SoftDeletes ;
    protected $guarded = [];

    public static function boot()
     {
        parent::boot();
        static::creating(function($model)
        {
            $user = Auth::user();
            $model->created_by = $user ? $user->id : null;
        });
        static::updating(function($model)
        {
            $user = Auth::user();
            $model->updated_by = $user ? $user->id : null;
        });
    }


    public function scopeFilter($query, $request)
    {
        
        if (isset($request['param'])) {
            foreach ($request['param'] as $key => $val) {
                switch ($val) {
                    case null:
                        $query->orWhere($val, 'like', '%' . $request['inputan'][$key] . '%');
                        break;
                    default:
                        $query->orWhere($val, 'like', '%' . $request['inputan'][$key] . '%');
                        break;
                }
            }
        }
        
        // dd($query);
        return $query;
    }

    public static function columns()
    {
        return columns([
            'Name' => 'string',
        ]);
    }

    public static function fields()
    {
        return fields([
           
            'Name' => 'string',
            'Action' => array(
                "show" => 'role',
                "edit" => 'role',
                "delete"  => 'role'
            ),
           
        ]);
    }

    public function menus()
    {
        return $this->belongsToMany(Menu::class, 'menu_role')->orderBy('count');
    }

    
    public function getMenusaAttribute()
    {
        dd($this->menus);
        return $this->menus ? $this->menus->name : '-';
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use App\Models\Role;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class RoleController extends Controller
{
    protected $models;
    public function __construct(Role $models)
    {
        $this->models = $models;
    }

    /**
     * Display a listing of the resource.
     */
    

    public function index(Request $request)
    {
        // dd(auth()->user()->menusa);
            $search = [];
            if ($request->all()) {
                $search = $request->all();
            }
       
            $create = 'role/create';
            $data = Role::filter($search)->latest()->paginate(10);
            $data = $this->list($data, $this->models, $create, 'Role Management');

            return view('template.index', $data);
    }

    public function create() {
        $datas = Role::latest()->pluck('name', 'id')->toArray();
        // dd($datas);
        $data['datas']['datas'] = fields([
            'Name' => array('type' => 'text', 'col' => 3, 'required' =>true),
        ]);

        $data['title'] = 'Role Management';
        $data['datas']['route'] = 'role.store';
        $data['datas']['method'] = 'POST';
       


        return view('template.create', $data);
    }

    public function store(Request $request) {
        DB::beginTransaction();

        try {
            \Illuminate\Support\Facades\Log::info(json_encode($request->all()));
           
            
            $role = Role::updateOrCreate([
                'id' =>$request->id],
                [
                'name'     => $request->name,
            ]);  
    
            session()->flash('message', 'Save Success.');

            DB::commit();
            return redirect('role'); 
        } catch (\Exception $e) {
            DB::rollBack();
            \Illuminate\Support\Facades\Log::error($e);
            // dd($e); 

            session()->flash('error', 'Failed Save.');
           return redirect()->back();   
        }
    
        
    }


    public function edit($id) {

        $datas = Role::latest()->pluck('name', 'id')->toArray();
        $data['datas']['datas'] = fields([
            'Id' => array('type' => 'hidden', 'col' => 12),
            'Name' => array('type' => 'text', 'col' => 3, 'required' =>true),
        ]);


        $data['title'] = 'Role Management';
        $data['datas']['route'] = 'role.store';
        $data['datas']['method'] = 'POST';
        $data['datas']['data'] = Role::find($id);



        return view('template.create', $data);
    }

    public function show($id) {

        $data['datas'] = Menu::where('menu_id', NULL)->get();
        $data['group'] = $this->models->find($id);
        $data['title'] = 'Role';
        $data['id'] = $id;
       // dd($data['group']->menus);
        return view('role.group', $data);
    }

    public function destroy($id)  {
        DB::beginTransaction();

        try {

            $find = Role::find($id)->update(['deleted_by' => auth()->user()->id,'deleted_at' => date('Y-m-d H:i:s')]);
            session()->flash('message', 'Delete Success.');

            DB::commit();
            return redirect('role'); 
        } catch (\Exception $e) {
            DB::rollBack();
            \Illuminate\Support\Facades\Log::error($e);
            session()->flash('error', 'Failed Save.');
           return redirect()->back();
        }
    }
}

resources/views/role/group.blade.php
@extends('layouts.apps')

@section('title')
{{$title}}
@endsection

@section('content')



<div class="card">
    <div class="card-body">
        <div class="row">
            <form action="{{ route('rolemenu.store') }}" method="post">
                @csrf
                <input type="hidden" name="id" id="" value="{{$id}}">
                <ul>
                    @foreach ($datas as $item)
                        <li>
                            @php
                                $selected = '';

                                foreach ($group->menus as $val) {
                                if ($val->id == $item->id) {
                                    $selected = 'checked';
                                    break;
                                }
                                }
                            @endphp
                            <input type="checkbox"
                           
                           
                            id="menu_{{ $item->id }}" {{$selected}} name="selected_menus[]" value="{{ $item->id }}">
                            {{ $item->name }}
                        </li>
                        @if ($item->details->count())
                            {!! printMenu($item->details,$group, 'menu_'.$item->id) !!}
                        @endif
                    @endforeach
                </ul>
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
        </div>
    </div>
</div>
@endsection
@php
    function printMenu($items,$group) {
        $html = '<ul>';
        foreach ($items as $item) {
                $selected = '';
                foreach ($group->menus as $val) {
                    if ($val->id == $item->id) {
                        $selected = 'checked';
                        break;
                    }
                }
            $html .= ' <li> <input type="checkbox"
                    '. $selected.' id="menu_'.$item->id.'" name="selected_menus[]" value="'.$item->id.'">' . $item->name . '</li>';
            if ($item->details->count()) {
                $html .= printMenu($item->details,$group);
            }
        }
        $html .= '</ul>';

        return $html;
    }
@endphp